'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useAuth } from '@/lib/auth-context';
import { fetchEvent } from '@/lib/events-api';
import { fetchMatchDetail } from '@/lib/matches-api';
import { Card, CardHeader, CardTitle, CardDescription } from '@/app/components/ui/card';
import type { Event } from '@/lib/types';
import type { Match } from '@/lib/types';

export default function MatchDetailPage() {
  const params = useParams();
  const { accessToken } = useAuth();
  const eventId = params.id as string;
  const matchId = params.matchId as string;
  const [event, setEvent] = useState<Event | null>(null);
  const [match, setMatch] = useState<
    (Match & { profile_summary?: string; strategy?: string; explanation?: string }) | null
  >(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!accessToken || !eventId || !matchId) return;
    let mounted = true;
    Promise.all([
      fetchEvent(accessToken, eventId).then((r) => r.data),
      fetchMatchDetail(accessToken, eventId, matchId).then((r) => r.data),
    ])
      .then(([ev, m]) => {
        if (mounted) {
          setEvent(ev ?? null);
          setMatch(m ?? null);
          setLoading(false);
        }
      })
      .catch(() => {
        if (mounted) {
          setError('Failed to load');
          setLoading(false);
        }
      });
    return () => {
      mounted = false;
    };
  }, [accessToken, eventId, matchId]);

  if (loading && !match) {
    return (
      <div className="flex justify-center py-12">
        <span className="inline-block size-8 animate-spin rounded-full border-2 border-[var(--accent)] border-t-transparent" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center gap-2">
        <Link href="/events" className="link text-sm">
          Events
        </Link>
        <span className="text-[var(--muted)]">/</span>
        <Link href={`/events/${eventId}`} className="link text-sm truncate">
          {event?.title ?? eventId}
        </Link>
        <span className="text-[var(--muted)]">/</span>
        <Link href={`/events/${eventId}/matches`} className="link text-sm">
          Matches
        </Link>
        <span className="text-[var(--muted)]">/</span>
        <span className="text-sm font-medium truncate">Match detail</span>
      </div>

      {error && (
        <Card>
          <p className="text-[var(--destructive)]">{error}</p>
        </Card>
      )}

      {!error && match && (
        <>
          <div>
            <h1 className="text-2xl font-semibold text-[var(--foreground)]">Match detail</h1>
            <p className="mt-1 text-sm text-[var(--muted)]">
              Profile summary and approach suggestions for this event.
            </p>
          </div>

          <Card>
            <CardHeader>
              <CardTitle>Profile summary</CardTitle>
              <CardDescription>
                Overview of the matched attendee (from resume/profile and P4/P6 in pipeline).
              </CardDescription>
            </CardHeader>
            <div className="prose prose-sm max-w-none text-[var(--foreground)]">
              {match.profile_summary ? (
                <p className="whitespace-pre-wrap">{match.profile_summary}</p>
              ) : (
                <p className="text-[var(--muted)]">No profile summary available yet.</p>
              )}
            </div>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Approach suggestions</CardTitle>
              <CardDescription>
                Strategy generated by LLM (P5) with guardrails; cached for fast retrieval (P6).
              </CardDescription>
            </CardHeader>
            <div className="prose prose-sm max-w-none text-[var(--foreground)]">
              {match.strategy ? (
                <p className="whitespace-pre-wrap">{match.strategy}</p>
              ) : (
                <p className="text-[var(--muted)]">
                  Suggestions will appear when the strategy is generated.
                </p>
              )}
            </div>
          </Card>

          {match.explanation && (
            <Card>
              <CardHeader>
                <CardTitle>Why this match</CardTitle>
                <CardDescription>Explainability from match scoring (P4).</CardDescription>
              </CardHeader>
              <p className="whitespace-pre-wrap text-[var(--foreground)]">{match.explanation}</p>
            </Card>
          )}

          <div className="flex gap-3">
            <Link href={`/events/${eventId}/matches`}>
              <span className="btn btn-secondary">← Back to matches</span>
            </Link>
            <Link href={`/events/${eventId}`}>
              <span className="btn btn-ghost">Event detail</span>
            </Link>
          </div>
        </>
      )}

      {!error && !match && !loading && (
        <Card>
          <p className="text-[var(--muted)]">Match not found.</p>
          <Link href={`/events/${eventId}/matches`} className="link mt-2 inline-block">
            Back to matches
          </Link>
        </Card>
      )}
    </div>
  );
}
