from enum import Enum


class ErrorCode(str, Enum):
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    EVENT_NOT_PUBLISHED = "EVENT_NOT_PUBLISHED"
    EVENT_CANCELLED = "EVENT_CANCELLED"
    EVENT_FULL = "EVENT_FULL"
    EVENT_CAPACITY_TOO_LOW = "EVENT_CAPACITY_TOO_LOW"
    EVENT_STARTS_AT_TOO_SOON = "EVENT_STARTS_AT_TOO_SOON"
    RSVP_CUTOFF_PASSED = "RSVP_CUTOFF_PASSED"
    RSVP_ALREADY_EXISTS = "RSVP_ALREADY_EXISTS"
    RSVP_NOT_FOUND = "RSVP_NOT_FOUND"
    EVENT_JOIN_CODE_EXISTS = "EVENT_JOIN_CODE_EXISTS"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    FORBIDDEN = "FORBIDDEN"
